select ABS (50.50) from dual;
select ABS (50.70) from dual;
select ABS (-50.50) from dual;
select MOD(10,3) from dual;
select power(10,2) from dual;
select power(-10,-2) from dual;
select round(10.56) from dual;
select round(10.3) from dual;
select round(-10.5) from dual;
select round(-10.1) from dual;
-- select TRUNC (50,2) from dual;
select SIN(0) from dual;
select SIN(45) from dual;
select SIN(30) from dual;
select SIN(60) from dual;
select SIN(90) from dual;
select COS(0) from dual;
select COS(30) from dual;
select COS(45) from dual;
select COS(60) from dual;
select COS(90) from dual;
select TAN(0) from dual;
select TAN(30) from dual;
select TAN(45) from dual;
select TAN(60) from dual;
select TAN(90) from dual;
select asin(1) from dual;
select asin(-1) from dual;
select asin(0.1) from dual;
select asin(0.5) from dual;
select asin(0) from dual;
select acos(1) from dual;
select acos(0.9) from dual;
select acos(-0.9) from dual;
select acos(-1) from dual;
select atan(30) from dual;
select atan(90) from dual;
select atan(0) from dual;
select atan(-90) from dual;
-- select SINH(360) from dual; 
-- select COSH(256) from dual;
-- select COSH(0) from dual;
-- select TANHA(0) from dual;
-- select TANHA(90) from dual;
select sqrt(25) from dual;
select sqrt(5) from dual;
select exp(25) from dual;
select exp(5) from dual;
select exp(625) from dual;
select ln(1) from dual;
select ln(10) from dual;
select ln(20) from dual;
select ln(30) from dual;
select log(2,200) from dual;
select log(10,200) from dual;
select log(200,200) from dual;
select ceil(20.5) from dual;
select ceil(-20.5) from dual;
select ceil(-20.1) from dual;
select ceil(20.1) from dual;
select floor(20.1) from dual;
select floor(20.5) from dual;
select floor(20.9) from dual;
select floor(-20.9) from dual;
select floor(-20.1) from dual;
select sign(20) from dual;
select sign(-20) from dual;
select sign(0) from dual;